name: Michael Lanyon's Blog
url: 'http://blog.lanyonm.org'
description: 'Notes and thoughts from LanyonM'

exclude: [Gemfile, Gemfile.lock, README.md]
highlighter: pygments

author: 'Michael Lanyon'
disqus_shortname: lanyonm
google_analytics: UA-42209870-1
